---
title: UATAQ Status Dashboard
---
<!-- Ben Fasoli -->

```{r setup}
library(dplyr)
library(flexdashboard)
library(plotly)
library(sendmailR)

# Find sites with <3 active references
stats <- readRDS('data/stats.rds')
needs_tank <- stats$site[stats$n_co2 < 3] %>% 
  na.omit %>%
  paste(collapse = ', ')

# Find sites with recent data reports
recent <- readRDS('data/airmap.rds')$fixed
new_mask <- recent$Time_UTC >= (Sys.time() - 3600 * 1.5)
needs_data <- recent$site[!new_mask] %>%
  paste(collapse = ', ')
```


Row
--------------------------------------------------------------------------------

### Sites Online (`r strftime(Sys.time(), '%H:%M %Z')`) `r if (nchar(needs_data) > 0) paste(' - Inactive:', needs_data)`
```{r}
pct <- length(which(recent$Time_UTC >= (Sys.time() - 3600 * 1.5))) /
  nrow(recent) * 100
# if (pct < 70) {
#   sendmail(from = '<donotreply@air.utah.edu>',
#            to   = '<benfasoli@gmail.com>',
#            subject = 'UATAQ Site Problems!',
#            msg     = 'Generated by dash_src.rmd. If this was sent in error, contact benfasoli@gmail.com',
#            control = list(smtpServer="ASPMX.L.GOOGLE.COM"))
# }
gauge(round(pct), min = 0, max = 100, symbol = '%',
      gaugeSectors(c(99, 100), c(70, 98), c(0, 69)))
```

### Min 3 Active Reference Tanks `r if (nchar(needs_tank) > 0) paste(' - Deficit:', needs_tank)`
```{r}
tmp <- stats$n_co2 %>% na.omit()
pct <- length(which(tmp > 2)) / (length(tmp)) * 100
gauge(round(pct), min = 0, max = 100, symbol = '%',
      gaugeSectors(c(99, 100), c(80, 98), c(0, 79)))
```

### `r strftime(Sys.time(), '%B', 'UTC')` Data Recovery Rate
```{r}
mo <- stats %>%
  filter(site == 'Total')
pct <- mo$data_recovery_rate * 100
gauge(round(pct), min = 0, max = 100, symbol = '%',
      gaugeSectors(success = c(90, 100),
                   warning = c(85, 89),
                   danger  = c(0, 84)))
```


Row {data-height=350}
--------------------------------------------------------------------------------

### CO$_2$ Calibrated <span style="float:right;"><a href="https://air.utah.edu/s/view/diagnostics/"><i class="fa fa-bar-chart"></i>Go To Site Diagnostics</a></span>
```{r}
plotly::ggplotly(readRDS('data/ts_co2.rds'), dynamicTicks = T)
```

### CH$_4$ Calibrated
```{r}
plotly::ggplotly(readRDS('data/ts_ch4.rds'), dynamicTicks = T)
```

Row {data-height=250}
--------------------------------------------------------------------------------

### CO$_2$ Average Diel Concentration
```{r}
plotly::ggplotly(readRDS('data/diurnal_co2.rds'), dynamicTicks = T)
```

### CH$_4$ Average Diel Concentration
```{r}
plotly::ggplotly(readRDS('data/diurnal_ch4.rds'), dynamicTicks = T)
```

Row {data-height=250}
--------------------------------------------------------------------------------

### CO$_2$ Average Diel Standard Deviation
```{r}
plotly::ggplotly(readRDS('data/diurnal_co2_sd.rds'), dynamicTicks = T)
```

### CH$_4$ Average Diel Standard Deviation
```{r}
plotly::ggplotly(readRDS('data/diurnal_ch4_sd.rds'), dynamicTicks = T)
```

<!-- Row -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ### CO$_2$ Pre-calibration Bias -->
<!-- ```{r} -->
<!-- val <- mo$bias_co2 -->
<!-- color <- -->
<!--   if (val < 4) { -->
<!--     'success' -->
<!--   } else if (val >= 4 && val < 6) { -->
<!--     'warning' -->
<!--   } else { -->
<!--     'danger' -->
<!--   } -->
<!-- txt <- paste(signif(val, 2), 'ppm') -->
<!-- flexdashboard::valueBox(txt, color = color, icon = 'fa-area-chart') -->
<!-- ``` -->

<!-- ### CO$_2$ Regression RMSE -->
<!-- ```{r} -->
<!-- val <- mo$rmse_co2 -->
<!-- color <- -->
<!--   if (val < 0.4) { -->
<!--     'success' -->
<!--   } else if (val >= 0.4 && val < 0.8) { -->
<!--     'warning' -->
<!--   } else { -->
<!--     'danger' -->
<!--   } -->
<!-- txt <- paste(signif(val, 2), 'ppm') -->
<!-- flexdashboard::valueBox(txt, color = color, icon = 'fa-tachometer') -->
<!-- ``` -->

<!-- ### CH$_4$ Pre-calibration Bias -->
<!-- ```{r} -->
<!-- val <- mo$bias_ch4 * 1000 -->
<!-- color <- -->
<!--   if (val < 18) { -->
<!--     'success' -->
<!--   } else if (val >= 18 && val < 30) { -->
<!--     'warning' -->
<!--   } else { -->
<!--     'danger' -->
<!--   } -->
<!-- txt <- paste(round(val), 'ppb') -->
<!-- flexdashboard::valueBox(txt, color = color, icon = 'fa-area-chart') -->
<!-- ``` -->

<!-- ### CH$_4$ Regression RMSE -->
<!-- ```{r} -->
<!-- val <- mo$rmse_ch4 * 1000 -->
<!-- color <- -->
<!--   if (val < 4) { -->
<!--     'success' -->
<!--   } else if (val >= 4 && val < 6) { -->
<!--     'warning' -->
<!--   } else { -->
<!--     'danger' -->
<!--   } -->
<!-- txt <- paste(round(val), 'ppb') -->
<!-- flexdashboard::valueBox(txt, color = color, icon = 'fa-tachometer') -->
<!-- ``` -->


Row {data-height=250}
--------------------------------------------------------------------------------

### CO$_2$ Pre-calibration Bias

```{r} 
plotly::ggplotly(readRDS('data/cal_offset_co2.rds'), dynamicTicks = T)
```

### CH$_4$ Pre-calibration Bias

```{r}
plotly::ggplotly(readRDS('data/cal_offset_ch4.rds'), dynamicTicks = T)
```


Row {data-height=250}
--------------------------------------------------------------------------------

### CO$_2$ Regression RMSE

```{r} 
plotly::ggplotly(readRDS('data/rmse_co2.rds'), dynamicTicks = T)
```

### CH$_4$ Regression RMSE

```{r}
plotly::ggplotly(readRDS('data/rmse_ch4.rds'), dynamicTicks = T)
```
