---
title: UATAQ Historic Carbon Dioxide
---
<!-- Ben Fasoli -->

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(dygraphs)
library(tidyverse)
library(xts)

historic <- readRDS('/home/benfasoli/cron/air.utah.edu/data/historic.rds') %>%
  na.omit()
historic$Site[historic$Site == 'imc'] <- 'mur'
historic$Site[historic$Site == 'wbb'] <- 'uou'
historic$Site <- toupper(historic$Site)

dplot <- function(x, colors = NULL) {
  if (!is.null(colors)) {
    colors <- RColorBrewer::brewer.pal(5, 'Set2')[colors]
  } else {
    colors <- RColorBrewer::brewer.pal(5, 'Set2')
  }
  
  dygraph(x, group = 'sync') %>%
  dyAxis('y', label = 'CO2 (ppm)') %>%
  dyOptions(colors = colors,
            drawGrid = F,
            fillAlpha = 0.1)
}
```


Row {data-height=500}
--------------------------------------------------------------------------------

### Salt Lake Valley CO$_2$ Trends
```{r}
wide <- historic %>%
  group_by(Site, Time) %>%
  summarize_all(funs(mean(., na.rm = T))) %>%
  ungroup() %>%
  spread(Site, CO2_ppm)

x <- xts(select(wide, -Time), wide$Time)

dplot(x)
```

Row {data-height=240}
--------------------------------------------------------------------------------
### Daybreak (DBK)
```{r}
dplot(x$DBK, colors = 1)
```

Row {data-height=240}
--------------------------------------------------------------------------------
### Murray (MUR)
```{r}
dplot(x$MUR, colors = 2)
```

Row {data-height=240}
--------------------------------------------------------------------------------
### Rose Park (RPK)
```{r}
dplot(x$RPK, colors = 3)
```

Row {data-height=240}
--------------------------------------------------------------------------------
### Sugarhouse (SUG)
```{r}
dplot(x$SUG, colors = 4)
```

Row {data-height=240}
--------------------------------------------------------------------------------
### University of Utah (UOU)
```{r}
dplot(x$UOU, colors = 5)
```





