---
title: About UATAQ
---
<!-- Ben Fasoli -->

<div class="container-fluid" style="margin-top: 15px;">
<div class="panel panel-default span10 offset1">
<div class="panel-heading">
<h4 class="panel-title"> About UATAQ </h4>
</div>
<div class="panel-body">

"Climate change is one of the most pressing and difficult issues of our time, and we are committed to doing our part to respond to it through research, teaching, and operations at the University of Utah"
- University of Utah President David W. Pershing and Board of Trustees

The Utah Atmospheric Trace Gas & Air Quality (UATAQ) lab was started in 2013 as a joint effort between the Global Change and Sustainability Center, the Department of Biology and the Department of Atmospheric Science. The mission of the lab is to collect and analyze long term, high frequency, high precision, and spatially variable trace gas and air quality data with the aim of understanding the spatial distribution and long term trends throughout Salt Lake Valley and Northern Utah. Building on the work of one of the founding members, Dr. Jim Ehleringer, the lab has been responsible for improving and expanding existing networks of instrumentation, developing and implementing new networks with different aims, and building an on campus facility for research, development, and student outreach. UATAQ specializes in the long term measurement of both mobile and in-situ trace gas and criteria pollutants. Our data is calibrated to international standards and we possess numerous years of experience in collecting trace gas data, including one of the longest continuous urban CO2 records in the nation.

#### Research Information
[AGU Fall 2015 Presentations](http://air.utah.edu/s/archive/aguf2015/)  
Mobile pollutant measurement platforms (Fasoli), High resolution emissions model comparisons (Mendoza)  
[LAIR Home](http://lair.utah.edu)  
Land-Atmosphere Interactions Research (LAIR) group home

#### People
[Ben Fasoli](http://benfasoli.com)  
Student Director

[Ryan Bares](mailto:ryan.bares@utah.edu)  
UATAQ Lab Manager

[John C. Lin](http://lair.utah.edu)  
Associate Professor, Atmospheric Sciences

[David Bowling](http://biologylabs.utah.edu/bowling/)  
Associate Professor, Biology

[James Ehleringer](http://www.biology.utah.edu/people/details.php?id=104)  
Distinguished Professor, Biology


#### Support
Funding sources for the lab include the Department of Energy, the National Oceanic and Atmospheric Administration (NOAA), the Global Change and Sustainability Center, and the Sustainable Campus Initative at the University of Utah.

</div>
</div>
</div>
